export const LOGIN = '/login'
export const PRODUCTS = '/products'
export const CART = '/cart'
export const CHECKOUT_ADDRESS = '/checkout-address'
export const CHECKOUT_PAYMENT = '/checkout-payment'
export const CONFIRMATION = '/confirmation'
export const ERROR = '/error'